# Generated by Django 6.0.3 on 2026-04-16 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('age_rating', models.CharField(choices=[('L', 'Livre'), ('10', 'Não recomendado para menores de 10 anos'), ('12', 'Não recomendado para menores de 12 anos'), ('14', 'Não recomendado para menores de 14 anos'), ('16', 'Não recomendado para menores de 16 anos'), ('18', 'Não recomendado para menores de 18 anos')], max_length=2)),
                ('genre', models.CharField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Ficção Científica', 'Ficção Científica'), ('Terror', 'Terror'), ('Suspense', 'Suspense'), ('Romance', 'Romance'), ('Fantasia', 'Fantasia'), ('Musical', 'Musical'), ('Documentário', 'Documentário')], max_length=50)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('showtime', models.TimeField()),
                ('theater', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='SeatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.session')),
            ],
            options={
                'unique_together': {('session', 'seat')},
            },
        ),
    ]
