# Generated by Django 6.0.3 on 2026-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8),
        ),
    ]
