# Generated by Django 6.0.3 on 2026-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
