name: CineReserve CI Pipeline

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "CELERY_BROKER_URL=redis://redis:6379/0" >> .env
          echo "FLW_PUBLIC_KEY=${{ secrets.FLW_PUBLIC_KEY }}" >> .env
          echo "FLW_SECRET_KEY=${{ secrets.FLW_SECRET_KEY }}" >> .env
          echo "FLW_ENCRYPTION_KEY=${{ secrets.FLW_ENCRYPTION_KEY }}" >> .env
          echo "FLW_SECRET_HASH=${{ secrets.FLW_SECRET_HASH }}" >> .env
          echo "FLW_REDIRECT_URL=${{ secrets.FLW_REDIRECT_URL }}" >> .env

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Show containers
        run: docker compose ps

      - name: Wait for database
        run: sleep 15
      
      - name: Run makemigrations
        run: docker compose exec web python cinereserve_api/manage.py makemigrations
      
      - name: Run migrations
        run: docker compose exec web python cinereserve_api/manage.py migrate

      - name: Run tests
        run: |
          docker compose exec -T web bash -c "
          cd cinereserve_api &&
          python manage.py test
          "

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Shutdown
        if: always()
        run: docker compose down